---
name: tag latest commit

on:
  push:
    branches:
      - master

jobs:
  performLinting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest version
        uses: actions/checkout@v2

      - name: lint yaml
        uses: ibiqlik/action-yamllint@master

  createRelease:
    needs: performLinting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest version
        uses: actions/checkout@v2

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.${{ steps.buildnumber.outputs.build_number }}"
          release_name: "v1.0.${{ steps.buildnumber.outputs.build_number }}"
          draft: false
          prerelease: false

      - name: Mark current build as the latest build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"

      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
